### ISSUE TITLE
Week 4 Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [yperea/quiron#1]
Nice job implementing hibernate into your project! I like your approach with the AppRepository interface/implementation.  Good use of Lombok too - isn't it nice to slim down the size of your classes?

**Comment by yperea** [comment]
Thanks! I'm replicating the pattern used in .NET when you work with Entity Framework. 

Project Lombok is great! I was reviewing the problem I had earlier with my Foreign Key and with a few annotations from both (Hibernate and Lombok) I avoided a lot of code. 

This is all that I had to implement in the Country property of the class State to make it work.

    @NonNull
    @EqualsAndHashCode.Exclude
    @ToString.Exclude
    @ManyToOne
    @JoinColumn(name = "CountryID")
    private Country country;
