### ISSUE TITLE
Code Review for Indie Project Quiron

### ISSUE THREAD

**Issue by drmiller1** [yperea/quiron#5]
# Design/Code Review 3

#### Reviewer: Dan Miller

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Project Overview**|| |
||Which planned functionality has been met? | It looks like most of the planned functionality has been met.   |
|| What planned functionality has not been met? ||
||Describe the GitHub history and what it demonstrates about the project progress during the semester.| The Github history shows that the different types of functionality covered in class was added to the project around the same time. |
||Describe how peer and instructor feedback/recommendations were incorporated into the project.| |
||Other comments/notes?| |
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.| Very nice use of Bootstrap templates.  All pages have a similar look and feel.  The pages are very professional looking.  The data validation is also well done.  All of the fields I skipped display a highlighted user friendly message asking the user to fill in the value.|
||Other comments/notes? | |
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation | The code is very well organized in Intellij.  The folders have meaningful names and contain code specific to those names.  Most of the classes are small and the methods are specific to its function. | 
||Other comments/notes?| The QAPlug tools were used to analyze the code.  There were a number of  efficiency issues pointed out (duplicate literals, unused imports, unused local variables, printing of stack trace, string literal equality issues (use of == or != instead of .equals()).  I would recommend using this tool to analyze the code and walk through the results to find some quick fixes that could be made. |
|**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy|The code for this project contains quite a bit of logging.  Most of the logging types are used (info, debug, error, and trace)  There are a few cases of "StackTrace()" being used in the ApiMedicManager and PropertiesLoader, but there aren't many.  No "System.out.printlns" were found in the code.  |Other comments/notes?| |
|**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After
||Other comments/notes?| |
|**Security**|Evaluate authentication/authorization:| |
||Is it implemented correctly and working locally as well as on AWS?
||Other comments/notes?| |
|**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is  error handling of the service implemented? For example, what happens if the service is not available?| |
||Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?|AWS Code Pipeline |
||Is the independent research topic/technique implemented in the project?| There are a number of independent research topics used in this project.  The topics I immediately noticed are Project Lombok, JQuery, and Bootstrap. |
||Other comments/notes?| |
|**Deployment**| Has the application been successfully deployed to AWS?| Yes, the application has been deployed to AWS. |
||Is the hosted application fully functioning?| No, the application is not fully functioning.  When I try to login, I enter all of the required information, hit the "Sign Up" button, and receive a hibernate exception splash screen.  |
||Other comments/notes?| |

**Comment by pawaitemadisoncollege** [comment]
@drmiller1 Just checking in on this to make sure you know values are missing for the code review. remember to include results from the code quality tool inspection (list of tools in week 14).

**Comment by yperea** [comment]
The website is completed and deployed on AWS. The most critical recommendations from QAPlug were implemented; however, still work in progress.
