### ISSUE TITLE
Instructor Feedback  - Week 15

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [yperea/quiron#6]
You've put a LOT of thought and work into this project and it shows! Lots and lots to be proud of here! I'm looking forward to seeing the final demo.

- [x] Is your time log up to date? Last entry right now is 11/18?
- [x] Are you planning to update JOURNAL.md for your work? If not, it should be removed.
- [x] Might be nice to check off completed tasks in the project plan using -[x]
- [x] Update readme.md with final technologies used including all libraries/services.
- [x] What is the user experience when something goes wrong, i.e., the database is down? Custom error page/s can help with this and can be set up in web.xml.
- [x] Check for javadoc on all classes/methods. For example ApiMedic.
- [ ] This line appears a few times, is there a better way? int responseStatusCode = 400; I think there are a few options, here is one: https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html
- [x] If this method were to throw exception, then you could use logging rather than printing stack traces to the console. https://github.com/yperea/quiron/blob/56b68f975c121348a57d76af7b8770175a8bdd2d/src/main/java/co/net/quiron/util/PropertiesLoader.java#L21-L30
- [x] Some duplicate lines of code that could be refactored. Examples: AccessDenied class  and https://github.com/yperea/quiron/blob/56b68f975c121348a57d76af7b8770175a8bdd2d/src/main/java/co/net/quiron/controller/account/Credential.java#L27-L36 and https://github.com/yperea/quiron/blob/56b68f975c121348a57d76af7b8770175a8bdd2d/src/main/java/co/net/quiron/controller/account/Credential.java#L47-L57.
- [x] If you and/or your code review partner have not yet run your code through one of the code quality tools, I'd recommend it to help identify other areas for improvement.
- [x] Clean up unused or dead code. Or if this is commented out for a reason, add a comment or TODO. https://github.com/yperea/quiron/blob/56b68f975c121348a57d76af7b8770175a8bdd2d/src/test/java/co/net/quiron/application/account/AccountManagerTest.java#L41-L71
- [x] Some unit tests could be updated to use .equals on the entity rather than comparing the various instance vars. https://github.com/yperea/quiron/blob/56b68f975c121348a57d76af7b8770175a8bdd2d/src/test/java/co/net/quiron/persistence/location/CountryRepositoryTest.java#L67-L68

**Comment by yperea** [comment]
I implemented most of the recommendations; however, about the one related with the "responseStatusCode = 400" sentence, I did not understand what should I do. 
For the point about unit testing, when assertEquals evaluates the two objects; although they are equal, JUnit fails the test because detects some differences in the format of the Date type fields.
